config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  get '/posts/all' => 'posts#all' 
  devise_scope :user do
    get '/users/all' => 'users/registrations#all'
    delete '/users/all' => 'users/registrations#remove'
    patch '/users/all' => 'users/registrations#toggleadmin'
    get '/users/all/edit' => 'users/registrations#adminedit'
    put '/users/all/edit' => 'users/registrations#adminupdate'
  end
  devise_for :users, controllers: {
	registrations: 'users/registrations'
      }
  resources :posts
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  paginates_per 5
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order(:updated_at).reverse_order.page(params[:page])

    #get a map of user id:name
    @users = Hash.new
    User.all.each do |user|
      @users[user.id] = user.fname + " " + user.lname
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.where("user_id = ?", current_user.id).reverse_order.page(params[:page])
  end

  def all
    #redirect to root if not logged in / not admin
    redirect_to root_path, warning: "You are not authorized" unless !current_user.nil? and current_user.admin?

    #order the list by latest updated date first
    @posts = Post.order(:updated_at).reverse_order.page(params[:page])

    #get a map of user id:email
    @users = Hash.new
    User.all.each do |user|
      @users[user.id] = user.email
    end

  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    post = Post.create!(post_params)
    post.update_attribute :user_id, current_user.id
  if post.save
      redirect_to post
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])
 
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end
 
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    if current_user.admin?
      redirect_to posts_all_path
    else
      redirect_to posts_path
    end
  end

private
  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update, :adminupdate]

  def all
    #redirect to root if not logged in / not admin
    redirect_to root_path, warning: "You are not authorized" unless !current_user.nil? and current_user.admin?
    @users = User.order(:id)
  end

  def adminedit
    @user = User.find(params[:format])
  end

  def adminupdate
    @user = User.find(params[:format])

    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
    end

    if @user.update(account_update_params)
      redirect_to users_all_path
    else
      render 'adminedit'
    end
  end

  def remove
    user = User.find(params[:format])
    user.destroy
 
    redirect_to users_all_path
  end

  def toggleadmin
    user = User.find(params[:format])
    user.update_attribute :admin, !user.admin
    redirect_to users_all_path
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fname, :lname, :email, :password])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:fname, :lname, :email, :password, :current_password])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<% content_for :title do %>
  <title>Home | RailsBBS</title>
<% end %>

<div class="container my-3">
  <% @posts.each do |post| %>
    <div class="card mb-3 border-dark">
      <% if post.image.attached? %>
        <image src="<%=(url_for(post.image))%>" class="card-img-top">
      <% end %>
      <div class="card-body">
        <h3 class="card-title"><%= post.title %></h3>
        <%= simple_format post.body, :class => "card-text"%>
        <br/>
        <p class="card-text small"><em>Updated at: <%= post.updated_at %> by 
          <% if @users[post.user_id].blank? %>
            removed
          <% else %>
            <%= @users[post.user_id] %>
          <% end %></em></p>
      </div>
    </div>
  <% end %>
  <%= paginate @posts %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if content_for?(:title) %>
      <%= content_for(:title) %>
    <% else %>
      <title>RailsBBS</title>
    <% end %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user.try(:admin?) %>
      <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
    <% else %>
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <% end %>
      <a class="navbar-brand" href="/">RailsBBS</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>

          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <li class="nav-item">
                <a class="nav-link" href="/users/all">All Users</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/posts/all">All Posts</a>
              </li>
            <% end %>
            <li class="nav-item">
              <a class="nav-link" href="/posts/new">New post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/posts">My posts</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.fname %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Edit User", edit_user_registration_path, method: :get, :class => 'dropdown-item'  %>
              <div class="dropdown-divider"></div>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'dropdown-item'  %>
              </div>
            </li>    
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, :class => 'nav-link'  %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link'  %>
            </li>
          <% end %>
          
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Not working" aria-label="Search">
          <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
        </form>

      </div>
    </nav>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_post_form.html.erb
<%= form_with model: @post, local: true do |form| %>
  <p>
    <%= form.label :title %><br/>
    <%= form.text_field :title, :class => "form-control my-2"  %>
  </p>
  <p>
    <%= form.label :body %><br/>
    <%= form.text_area :body, :class => "form-control my-2", :style => 'min-height: 200px'  %>
  </p>
 <p>
    Upload an image: 
    <%= form.file_field :image, :class => "form-control-file my-2" %>
  </p>
  <p>
    <%= form.submit "Submit Post", :class => "btn bg-primary btn-outline-light" %>
  </p>
<% end %>

app/views/posts/all.html.erb
<% content_for :title do %>
  <title>All Posts | RailsBBS</title>
<% end %>

<div class="container my-3">
<h1>All Posts</h1>
 
<table class="table table-striped">
  <tr scope="row">
    <th scope="col">Time</th>
    <th scope="col">User</th>
    <th scope="col">Title</th>
    <th scope="col">Body</th>
    <th scope="col"></th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr scope="row">
      <td><%= post.updated_at %></td>
      <td>
        <% if @users[post.user_id].blank? %>
          <em>removed (id:<%= post.user_id %>)</em>
        <% else %>
          <%= @users[post.user_id] %> (id:<%= post.user_id %>)
        <% end %>
      </td>
      <td><%= post.title %></td>
      <td><%= simple_format post.body %></td>
      <td>
        <%= link_to 'Show', post_path(post) %>
        <%= link_to 'Edit', edit_post_path(post) %>
        <%= link_to 'Delete', post_path(post),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>
<%= paginate @posts %>
</div>

app/views/posts/edit.html.erb
<% content_for :title do %>
  <title>Edit post | RailsBBS</title>
<% end %>

<div class="container my-3">
<h1>Edit post</h1>

<%= render 'post_form' %>
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<% content_for :title do %>
  <title>My Posts | RailsBBS</title>
<% end %>

<div class="container my-3">
<h1>My Posts</h1>
 
<table class="table table-striped">
  <tr scope="row">
    <th scope="col">Time</th>
    <th scope="col">Title</th>
    <th scope="col">Body</th>
    <th scope="col"></th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr scope="row">
      <td><%= post.updated_at %></td>
      <td><%= post.title %></td>
      <td><%= simple_format post.body %></td>
      <td>
        <%= link_to 'Show', post_path(post) %>
        <%= link_to 'Edit', edit_post_path(post) %>
        <%= link_to 'Delete', post_path(post),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>
<%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<% content_for :title do %>
  <title>New post | RailsBBS</title>
<% end %>

<div class="container my-3">
<h1>New post</h1>

<%= render 'post_form' %>
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="container">
<h1><strong><%= @post.title %></strong></h1>
 
<p><%= simple_format @post.body %></p>
<% if @post.image.attached? %>
  <p><image src="<%=(url_for(@post.image))%>" class="img-fluid"></p>
<% end %>
<%= link_to 'Edit', edit_post_path(@post) %>
<% if current_user.admin? %>
  <p><%= link_to 'Back', posts_all_path %></p>
<% else %>
  <p><%= link_to 'Back', posts_path %></p>
<% end %>
</div>